package com.epul.ergosum.metier;


// Generated 24 avr. 2014 11:38:54 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Catalogue generated by hbm2java
 */
public class Catalogue implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int annee;
	private int quantiteDistribuee;
	private Set<Comporte> comportes;

	public Catalogue() {
		comportes = new HashSet<Comporte>();
	}

	public Catalogue(int annee, int quantiteDistribuee) {
		this.annee = annee;
		this.quantiteDistribuee = quantiteDistribuee;
	}

	public Catalogue(int annee, int quantiteDistribuee, Set<Comporte> comportes) {
		this.annee = annee;
		this.quantiteDistribuee = quantiteDistribuee;
		this.comportes = comportes;
	}

	public int getAnnee() {
		return this.annee;
	}

	public void setAnnee(int annee) {
		this.annee = annee;
	}

	public int getQuantiteDistribuee() {
		return this.quantiteDistribuee;
	}

	public void setQuantiteDistribuee(int quantiteDistribuee) {
		this.quantiteDistribuee = quantiteDistribuee;
	}

	public Set<Comporte> getComportes() {
		return this.comportes;
	}

	public void setComportes(Set<Comporte> comportes) {
		this.comportes = comportes;
	}
	
	/**
	 * StatCategorie() => rechercherDictionnaire() dans GestionCatalogue
	 */
	
	@Override
	public boolean equals(Object obj) {
		if (obj == this) return true;
		if (obj == null) return false;
		if (obj instanceof Catalogue)
		{
			return this.getAnnee() == ((Catalogue)obj).getAnnee();
		}
		return false;
	}
}
