package com.epul.ergosum.metier;

// Generated 24 avr. 2014 11:38:54 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Jouet generated by hbm2java
 */
public class Jouet implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private String numero;
	private Categorie categorie;
	private Trancheage trancheage;
	private String libelle;
	private Set<Comporte> comportes;

	public Jouet() {
		comportes = new HashSet<Comporte>(0);
	}

	public Jouet(String numero, Categorie categorie, Trancheage trancheage, String libelle) {
		this.numero = numero;
		this.categorie = categorie;
		this.trancheage = trancheage;
		this.libelle = libelle;
	}

	public Jouet(String numero, Categorie categorie, Trancheage trancheage,
			String libelle, Set<Comporte> comportes) {
		this.numero = numero;
		this.categorie = categorie;
		this.trancheage = trancheage;
		this.libelle = libelle;
		this.comportes = comportes;
	}

	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	public Categorie getCategorie() {
		return this.categorie;
	}

	public void setCategorie(Categorie categorie) {
		this.categorie = categorie;
	}

	public Trancheage getTrancheage() {
		return this.trancheage;
	}

	public void setTrancheage(Trancheage trancheage) {
		this.trancheage = trancheage;
	}

	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	public Set<Comporte> getComportes() {
		return this.comportes;
	}

	public void setComportes(Set<Comporte> comportes) {
		this.comportes = comportes;
	}
	
	public void addComporte(Comporte c)
	{
		this.comportes.remove(c);
		this.comportes.add(c);
	}
	
	@Override
	public boolean equals(Object obj) {
		if (obj == this) return true;
		if (obj == null) return false;
		if (obj instanceof Jouet)
		{
			return this.getNumero().contentEquals(((Jouet) obj).getNumero());
		}
		return false;
	}

}
