package com.epul.ergosum.metier;

// Generated 24 avr. 2014 11:38:54 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Trancheage generated by hbm2java
 */
public class Trancheage implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private String codetranche;
	private Integer agemin;
	private Integer agemax;
	private Set<Jouet> jouets;

	public Trancheage() {
		jouets = new HashSet<Jouet>();
	}

	public Trancheage(String codetranche) {
		this();
		
		this.codetranche = codetranche;
	}

	public Trancheage(String codetranche, Integer agemin, Integer agemax,
			Set<Jouet> jouets) {
		this(codetranche);
		
		this.agemin = agemin;
		this.agemax = agemax;
		this.jouets = jouets;
	}

	public String getCodetranche() {
		return this.codetranche;
	}

	public void setCodetranche(String codetranche) {
		this.codetranche = codetranche;
	}

	public Integer getAgemin() {
		return this.agemin;
	}

	public void setAgemin(Integer agemin) {
		this.agemin = agemin;
	}

	public Integer getAgemax() {
		return this.agemax;
	}

	public void setAgemax(Integer agemax) {
		this.agemax = agemax;
	}

	public Set<Jouet> getJouets() {
		return this.jouets;
	}

	public void setJouets(Set<Jouet> jouets) {
		this.jouets = jouets;
	}
	
	public void addJouet(Jouet j)
	{
		this.jouets.add(j);
	}


	@Override
	public boolean equals(Object obj) {
		if (obj == this) return true;
		if (obj == null) return false;
		if (obj instanceof Trancheage)
		{
			return this.getCodetranche().contentEquals(((Trancheage)obj).getCodetranche());
		}
		
		return false;
	}
}
